name: Publish npm Package

on:
  push:
    branches:
      - main  # Trigger on merges to main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # Allow pushing tags
      packages: write   # Allow npm publish
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: https://npm.pkg.github.com

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Create release and publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
